### ISSUE TITLE
Adapter noch aktuell?

### ISSUE THREAD

**Issue by Siggi0904** [Omega236/ioBroker.virtualpowermeter#143]
Hallo,

ist der Adapter noch aktuell und kann dieser mit der aktuellen iobroker Umgebung verwendet werden?

Da lange nichts gemacht, könnte das aktuelle admin bzw. die nodejs Version nicht unterstützt werden.

Danke im Voraus.

**Comment by Omega236** [comment]
Ja der Adapter funktioniert mit der aktuellsten Version und ich habe die Pakete auch ma wieder aktualisiert.
