### ISSUE TITLE
 uncaught exception: Cannot read property

### ISSUE THREAD

**Issue by crunchip77** [Omega236/ioBroker.virtualpowermeter#35]
Verwendung des Adapters mit V 1.2.1.
Nachdem ich gerade ein Update des shelly Adapters von v3.2.6 auf v3.2.7, erhielt ich folgende Meldung.
`

host.IoBroker | 2020-05-05 09:42:40.762 | info | Restart adapter system.adapter.virtualpowermeter.0 because enabled
-- | -- | -- | --
host.IoBroker | 2020-05-05 09:42:40.761 | info | instance system.adapter.virtualpowermeter.0 terminated with code 0 (NO_ERROR)
virtualpowermeter.0 | 2020-05-05 09:42:38.804 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
virtualpowermeter.0 | 2020-05-05 09:42:38.804 | error | at Virtualpowermeter.onStateChange (/opt/iobroker/node_modules/iobroker.virtualpowermeter/main.js:70:51)
virtualpowermeter.0 | 2020-05-05 09:42:38.804 | error | (2013) TypeError: Cannot read property 'group' of undefined
virtualpowermeter.0 | 2020-05-05 09:42:38.796 | error | (2013) uncaught exception: Cannot read property 'group' of undefined
shelly.0 | 2020-05-05 09:42:38.511 | info | (13487) Shelly device 10.1.1.114 (shelly1 / xyz / SHSW-1#xyz#1) with CoAP connected!
shelly.0 | 2020-05-05 09:42:34.208 | info | (13487) Listening for Shelly packets in the network
shelly.0 | 2020-05-05 09:42:34.128 | info | (13487) Starting Shelly adapter in CoAP modus.
shelly.0 | 2020-05-05 09:42:34.058 | info | (13487) Starting Adapter shelly.0 in version 3.2.7
shelly.0 | 2020-05-05 09:42:34.017 | info | (13487) starting. Version 3.2.7 in /opt/iobroker/node_modules/iobroker.shelly, node: v10.20.1, js-controller: 3.0.20
host.IoBroker | 2020-05-05 09:42:29.833 | info | instance system.adapter.shelly.0 started with pid 13487

`
Der Zähler für "xyz.Script_Total" ist dadurch nun zurückgesetzt und beginnt bei 0

**Comment by Omega236** [comment]
Hier scheint wohl der Shelly-Adapter Datenpunkte zu löschen die nicht zu ihm gehören (sein gutes Recht :) )
In solch einem Fall können die Datenpunkte im VirtualPowermeter auch Absolut angegeben werden.

Sobald ein "." enthalten ist wird der Datenpunkt als Absolute Id betrachtet.

ich habe z.B. die Datenpunkte in den VirtualPower Gruppen Verzeichnis abgelegt (virtualpowermeter.0.group_SmartHome.shelly.0.SHSW-25#6927BB#1.online.Virtual_Energy_Power_Standby):
![grafik](https://user-images.githubusercontent.com/25373047/81096845-4d247780-8f07-11ea-8052-e2e4ba674d95.png)

also "virtualpowermeter.0.group_SmartHome." + die ObjectID + ".Virtual_Energy_Power_Standby"

ich hoffe das reicht als Antwort.
