### ISSUE TITLE
Please update stable with v1.2.1+

### ISSUE THREAD

**Issue by Apollon77** [Omega236/ioBroker.virtualpowermeter#36]
... to support the js.controller 3 release to stable next week. Thank you!

**Comment by Omega236** [comment]
ich weiß gerade nicht was fehlt.
Es scheint nur die http://iobroker.live/badges/virtualpowermeter-stable.svg in der readme noch  auf 1.0.0 zu sein.
Es sollte doch anpassend er https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist-stable.json ausreichen oder?

**Comment by Apollon77** [comment]
it is ok ... it seems the batches are cached sometimes very long :-(

**Comment by Apollon77** [comment]
so check www.iobroker.net -> Adapters ... there the versions are hown
