### ISSUE TITLE
VirtualPowerMeter auf Alias geht nicht

### ISSUE THREAD

**Issue by MikeHellracer** [Omega236/ioBroker.virtualpowermeter#38]
Der VPM funktioniert leider nicht auf einem Alias.

1. VPM auf einer Lampe aktiviert --> funktion OK. 
2. Über "Geräte" einen "Alias" für eine Lampe/dimmer erstellt. --> Der Alias funktioniert einwandfrei.
3. Danach aktiviere ich das VPM auf dem DP "ON_ACTUAL" des Alias und bekomme folgenden Fehler. 

virtualpowermeter.0 | 2020-10-01 22:35:04.454 | error | (25425) Error: Alias alias.0.boilingroom.light1.Virtual_Energy_Power has no target at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1588:72 at /opt/iobroker/node_modules/iobro
-- | -- | -- | --
virtualpowermeter.0 | 2020-10-01 22:35:04.448 | error | (25425) unhandled promise rejection: Alias alias.0.boilingroom.light1.Virtual_Energy_Power has no target
virtualpowermeter.0 | 2020-10-01 22:35:04.447 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
virtualpowermeter.0 | 2020-10-01 22:35:04.440 | warn | (25425) Alias alias.0.boilingroom.light1.Virtual_Energy_Power has no target 9

**Comment by Omega236** [comment]
Der VPM erzeugt normal die Datenpunkte im gleichen Verzeichnis wie der überwachte Datenpunkt. 

Der Adapter "Alias" bzw Geräte überwacht aber scheibar alle Datenpunkte in seinem Verzeichnis und versucht den Ursprungsdatenpunkt anzupassen (den es aber nicht gibt, da der VPM den Datenpunkt erzeugt hat). Der VPM mischt sich hier sozusagen unberechtigt ein, was einige Adapter nicht mögen, dafür sind aber die Datenpunkte einfach zuzuordnen.

Eine Möglichkeit das Problem zu umgehen ist, für "Datapointname for Power" und "Datapointname for Enery" einen Datenpunkt mit "." anzugeben, dann wird der Datenpunkt direkt hier abgelegt, z.B. "0_userdata.0.VPM.Virtual_Energy_Power_Lampe" oder auch "virtualpowermeter.0.Virtual_Energy_Power_Lampe".
Der Datenpunkt darf aber nicht im alias.0 verzeichnis sein.

**Comment by Omega236** [comment]
Ok jetzt versteh ich das Problem. 

Auch wenn man ein Alias auf einen bestehenden VPM DP erstellt schmiert der Adapter ab.

schau ich mir bei gelegenheit an

**Comment by Omega236** [comment]
#48
