### ISSUE TITLE
RGB Dimmer Channel summieren

### ISSUE THREAD

**Issue by Kev0123** [Omega236/ioBroker.virtualpowermeter#45]
**Describe the bug**  
Wenn bei einem RGB Dimmer bspw. aus artnet2 Adapter pro Kanal, also Rot Grün und Blau, ein Powermeter angelegt wird, wird lediglich einer gezählt.

**To Reproduce**  
Mehrere Powermeter pro device

**Expected behavior**  
Entweder mehrere Powermeter pro device summieren oder den Hex Wert als Quelle nehmen.

**Comment by Omega236** [comment]
Jeder Datenpunkt braucht umbedingt sein Eindeutiges Ziel, wenn also mehrere States im gleichen Ordner sind, musst du die ObjektNamen entsprechend anpassen (z.B. Virtual_Energy_Power_Rot und Virtual_energy_Total_Rot)

Man kann auch beim Datapointname einen Absoluten Pfad angeben (sobald ein "." im Name ist). Da einige Adapter es nicht mögen wenn man in ihren Datenpunkte eigene erstellt. Dafür kann man z.B. unter virtualpowermeter.0.group_xxx sie abzulegen (Aufpassen dass man nicht mehrere Datenpunkte auf die gleichen IDs legt)

![grafik](https://user-images.githubusercontent.com/25373047/104218659-5920eb80-543d-11eb-8e20-774822d489a7.png)

**Comment by Kev0123** [comment]
Okay danke so wird nen Schuh draus. Kannst du das ggf. abfangen um vorm anlegen zu checken ob schon ein "default - Virtual_Energy_Power" angelegt ist und nen fehler ausgeben? Ist nur nen nice to habe um so doofe User wie mich nicht zu verwirren 😉
