### ISSUE TITLE
Zähler wird bei reset von HM RPC gelöscht

### ISSUE THREAD

**Issue by Kev0123** [Omega236/ioBroker.virtualpowermeter#46]
**Describe the bug**  
Wenn die HM RPC Instanz neu startet wird der totale Zähler gelöscht.

**To Reproduce**  
HM RPC neu starten

**Expected behavior**  
Nur bei aktivem Löschen den Zähler resetten

**Comment by Omega236** [comment]
Hallo,

ich verwende auch den HM RPC habe das problem aber nicht. Wie sehen deine Config für den Datenpunkt aus? welches Gerät ist es?

notfalls kann man beim Datapointname auch einen Absoluten Pfad angeben (sobald ein "." im Name ist). Da einige Adapter es nicht mögen wenn man in ihren Datenpunkte eigene erstellt, ist es dann sinnvoll diese z.B. unter virtualpowermeter.0.group_xxx sie abzulegen (Aufpassen dass man nicht mehrere Datenpunkte auf die gleichen IDs legt)

![grafik](https://user-images.githubusercontent.com/25373047/104218659-5920eb80-543d-11eb-8e20-774822d489a7.png)

**Comment by Kev0123** [comment]
Ich habe die Einstellung bei jedem Datenpunkt einen Unterpunkt für den virtualpowermeter erstellen lassen.
Vermutlich mag der hm.rpc das nicht und killt die beim restart.

Gibts eine Möglichkeit die Datenpunkte z.b. per checkbox automatisch unter virtualpowermeter.0.group_xxx für die ausgewählten geräte anzulegen?
Wäre für den enduser komfortabeler als immer den absoluten anlegen zu müssen.

![Screenshot_20210111-204843](https://user-images.githubusercontent.com/19821853/104230919-7b6f3500-544e-11eb-9f70-3bb4345fda92.png)

**Comment by Omega236** [comment]
Hallo, ich hab es mal auf meine Toddo liste aufgenommen
#48
