### ISSUE TITLE
Datenpunkte bei Geräten mit mehreren Powerstates

### ISSUE THREAD

**Issue by ZZMajor** [Omega236/ioBroker.virtualpowermeter#5]
Wie [hier](https://forum.iobroker.net/topic/20247/adapter-virtualpowermeter/20#) im iobroker Forum beschrieben werden die beiden virtualpowermeter-Datenpunkte unter dem Gerät selbst nicht aktualisiert, wenn von einem Gerät mehr als ein Datenpunkt geloggt werden (z.B. einzelne Ausgänge von Mehrfachsteckdosen). Die separaten Gruppendatenpunkte von virtualpowermeter zählen sauber mit.

**Comment by Omega236** [comment]
#6 
in 1.0.0 umgesetzt
