### ISSUE TITLE
Error nach upgrade des Js-Controllers 3.2.x

### ISSUE THREAD

**Issue by crunchip77** [Omega236/ioBroker.virtualpowermeter#50]
mit dem Upgrade des Js-Controllers kommt nach dem iobroker gestartet wurde, folgende Meldung
`

virtualpowermeter.0 | 2021-01-16 14:17:45.860 | error | (20674) Could not check object existence of sonoff.0.Luefter.Virtual_Energy_Total: Error: Cannot check object existence of "sonoff.0.Luefter.Virtual_Energy_Total": Error: Connection is closed.
-- | -- | -- | --
virtualpowermeter.0 | 2021-01-16 14:17:45.859 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
virtualpowermeter.0 | 2021-01-16 14:17:45.859 | error | at Virtualpowermeter.setForeignObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3350:30)
virtualpowermeter.0 | 2021-01-16 14:17:45.859 | error | at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2252:17)
virtualpowermeter.0 | 2021-01-16 14:17:45.859 | error | (20674) Error: Could not check object existence of sonoff.0.Luefter.Virtual_Energy_Total: Error: Cannot check object existence of "sonoff.0.Luefter.Virtual_Energy_Total": Error: Connection is closed.
virtualpowermeter.0 | 2021-01-16 14:17:45.856 | error | (20674) unhandled promise rejection: Could not check object existence of sonoff.0.Luefter.Virtual_Energy_Total: Error: Cannot check object existence of "sonoff.0.Luefter.Virtual_Energy_Total": Error:
virtualpowermeter.0 | 2021-01-16 14:17:45.856 | error | (20674) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
virtualpowermeter.0 | 2021-01-16 14:17:45.835 | error | (20674) Cannot check object existence of "sonoff.0.Luefter.Virtual_Energy_Total": Error: Connection is closed.
virtualpowermeter.0 | 2021-01-16 14:17:44.471 | warn | (20674) Terminated (UNCAUGHT_EXCEPTION): Without reason
virtualpowermeter.0 | 2021-01-16 14:17:42.880 | error | (20674) Cannot read property 'group' of undefined
virtualpowermeter.0 | 2021-01-16 14:17:42.879 | error | at Virtualpowermeter.onStateChange (/opt/iobroker/node_modules/iobroker.virtualpowermeter/main.js:71:50)
virtualpowermeter.0 | 2021-01-16 14:17:42.879 | error | (20674) TypeError: Cannot read property 'group' of undefined
virtualpowermeter.0 | 2021-01-16 14:17:42.878 | error | (20674) unhandled promise rejection: Cannot read property 'group' of undefined
virtualpowermeter.0 | 2021-01-16 14:17:42.875 | error | (20674) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`
`virtualpowermeter.0 | 2021-01-16 15:13:53.055 | warn | (14200) Terminated (UNCAUGHT_EXCEPTION): Without reason
virtualpowermeter.0 | 2021-01-16 15:13:52.298 | error | (14200) Cannot read property 'group' of undefined
virtualpowermeter.0 | 2021-01-16 15:13:52.298 | error | (14200) TypeError: Cannot read property 'group' of undefined at Virtualpowermeter.onStateChange (/opt/iobroker/node_modules/iobroker.virtualpowermeter/main.js:72:51)
virtualpowermeter.0 | 2021-01-16 15:13:52.297 | error | (14200) unhandled promise rejection: Cannot read property 'group' of undefined
virtualpowermeter.0 | 2021-01-16 15:13:52.296 | error | (14200) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by Omega236** [comment]
Hast du mehr mehr Infos? Welche ja-Controller Version. 

Welche virtualpowermeter Version. 

File oder Redis?

**Comment by Omega236** [comment]
Erste Tests mit 3.2.6-4 laufen ohne Probleme, brauche also mehr Infos.

**Comment by crunchip77** [comment]
hatte heute begonnen den Js-Controller zu testen, siehe
<https://forum.iobroker.net/post/559437> , angefangen mit 3.2.3 bis 3.2.6,
daher ist es aufgefallen, beim testen jeder einzelnen Version.

virtualpowermeter Version ist 1.2.2

verwende objekte/file, state/redis


Am Sa., 16. Jan. 2021 um 16:45 Uhr schrieb Omega236 <
notifications@github.com>:

**Comment by Omega236** [comment]
Habe nun auf meinem zweiten TestSystem getestet (x86 linux Docker, Objekte und state redis)
js-controller  3.2.6-4
virtualpowermeter: 1.2.2 und 1.3.0

es läuft auch alles so wie es soll.

@crunchip77 kannst du mal die version installieren? https://github.com/Omega236/ioBroker.virtualpowermeter/tarball/1.3.0

Die Logs deuten auf einen getChangeState hin der nicht subscriped wurde.

**Comment by crunchip77** [comment]
installation funktioniert leider nicht.
$ ./iobroker url "
https://github.com/Omega236/ioBroker.virtualpowermeter/tarball/1.3.0"
install https://github.com/Omega236/ioBroker.virtualpowermeter/tarball/1.3.0
NPM version: 6.14.10npm install
https://github.com/Omega236/ioBroker.virtualpowermeter/tarball/1.3.0
--loglevel error --prefix "/opt/iobroker" (System call)
ERROR: host.IoBroker Cannot install
https://github.com/Omega236/ioBroker.virtualpowermeter/tarball/1.3.0: 0
ERROR: process exited with code 25

Am Sa., 16. Jan. 2021 um 19:22 Uhr schrieb Omega236 <
notifications@github.com>:

**Comment by Omega236** [comment]
Der fehler kommt jetzt bei mir auch, aber der 1.3.0 ist trotzdem installiert, einfach mal Adapter neu starten dann sollte man am log sehen dass die neue Version läuft ( log sagt zielverzeichnis).

kommt der Fehler immer noch?

**Comment by crunchip77** [comment]
ah ok, version zeigt er 1.3.0.
Habe nun iobroker gestoppt und wieder gestartet, diesmal keinen Fehler
diesbezüglich gefunden.

Am Sa., 16. Jan. 2021 um 19:55 Uhr schrieb Omega236 <
notifications@github.com>:
