### ISSUE TITLE
RGB Dimmer zählt trotz Switch state=false

### ISSUE THREAD

**Issue by Kev0123** [Omega236/ioBroker.virtualpowermeter#51]
Hi,
Habe nochmal ein Problem mit dem Zähler.

Wie hier beschrieben;
https://github.com/BenjaminHae/ioBroker.artnet2/issues/12

zählt der Verbrauchszähler weiter ohne das das Gerät eingeschaltet ist.

Die RGB Werte bleiben statisch, der Zähler dürfte erst auf Switchstate true anfangen zu zählen.

Gibts eine Lösung für das Problem?
Dürfte allgemein Geräte betreffen die einen Dimmwert speichern und erst auf State Ein/Aus schalten.

Grüße

**Comment by Omega236** [comment]
Ja das Problem kenne ich vom Zigbee Adapter. 
aktuell löse ich das Problem mit einem Script das beim ändern des states (on/off) die Prozentwerte über Update (nicht Befehl) auf 0% bzw auf den passenden %wert setzt. 

Ich schaue mal ob ich ne Idee habe wie man das im Adapter integrieren könnte

**Comment by Frank1604** [comment]
Ich hänge mich hier mal an und verschlimmere das Problem nochmals.

Ich habe ein Device welches einen Dimmwert und einen on/off Wert hat. Der Dimmwert bleibt bei On/Off unverändert. Um es aber noch schlimmer zu machen hat das Ding jeweils 2 dieser Werte, es ist ein Doppeldimmer. Wie bekomme ich das Ding in den Adapter rein?

![grafik](https://user-images.githubusercontent.com/10420590/107696159-e44a0700-6cb1-11eb-8faa-989337023aa8.png)

**Comment by Omega236** [comment]
@Frank1604 
Mit dem Problem on/off + Dimmer: aktuell nur wie in meinem oberen Post beschrieben: ein kleines hilfscript.

das Problem mit 2: bei beiden unterschiedliche Datenpunkte angeben z.b. eine 1 und 2 anhängen.. Und mit dem on/off + Dimmer: 2 hilfscripte

**Comment by Frank1604** [comment]
Naja, hilft wohl nichts anderes. Vielleicht fällt dir ja irgendwann eine Lösung dazu ein, so eine Art Abhängigkeit von einem weiteren Datenpunkt. Ungefähr so etwas wie: "Abhängiger Datenpunkt (bool) : Der Verbrauch wird nur gezählt wenn dieser Wert true ist".

Da ich die zuletzt eingestellten Werte aber brauche, werde ich wohl zusätzliche Datenpunkte anlegen die ich mittels Script befeuere. Danke aber für den Tipp mit der unterschiedlichen Benennung um die beiden Punkte in den Adapter zu bekommen, das ist ja eigentlich selbsterklärend und ich überlege gerade warum ich da nicht selbst drauf gekommen bin. Manchmal ist man irgendwie blind. :)

**Comment by Omega236** [comment]
So Version 1.4.0 kann nun damit umgehen.

installation heute über Github, ab morgen im latest. stable schau ich wann ich es übernehmen lasse, gab ja doch einige Änderungen.

So sieht es bei meinem Gerät aus:

![OptinalSwitch](https://user-images.githubusercontent.com/25373047/107817078-e83f5d00-6d75-11eb-852c-8d34e72fbf69.png)

**Comment by Frank1604** [comment]
Super, vielen Dank für die schnelle Implementierung!
