### ISSUE TITLE
timecounter integrieren :)

### ISSUE THREAD

**Issue by Troox73** [Omega236/ioBroker.virtualpowermeter#55]
Hi, es wäre schön wenn ein dritter Datenpunkt angelegt wird. Und zwar für die aktive Zeit des Verbrauchers. Sollte ja nicht schwer sein es zu berechnen, oder? Wird ja sicher eh für den VPM gebraucht. Würde auch ein iobroker.timecounter update überflüssig machen :-)

**Comment by Omega236** [comment]
Das ist jetzt schon möglich. 

Einfach eine neue Instanz vom Adapter erstellen also z.B. virtualpowermeter.1

und dann dem zu überwachendem Datenpunkt den Max Power setzen (1= Ergebnis in h, 60=Ergebnis in Minuten, 3600=Ergebnis in Sekunden). Dann den Zieldatenpunkt z.b Gesamtzeit nennen und nachdem er erstellt wurde die Einheit von Wh auf h m oder s(ekunden) ändern. 

Sollte nur die Zeit wichtig sein und die Power nicht, dann reicht eine Instanz

**Comment by Omega236** [comment]
Sollte das zu umständlich sein, kann ich mal darüber nachdenken es nativ einzubauen

**Comment by Troox73** [comment]
Nativ wäre cool, mein PI kratzt mit 2GB an seiner Ramgrenze ;-)
