### ISSUE TITLE
Datenpunkt für den Gruppen-verbrauch wird nachts neu erzeugt und auf 0 gesetzt

### ISSUE THREAD

**Issue by daniel-finger** [Omega236/ioBroker.virtualpowermeter#57]
Der Datenpunkt für Energy_Total für eine Gruppe wird nachts um 0 Uhr neu erzeugt.

2021-02-21 00:00:00.133 - info: sql.0 (19322) enabled logging of virtualpowermeter.0.group_light.Virtual_Energy_Total_group_light, Alias=false

Dabei wird der Verbrauch aber auch zurückgesetzt, was das sourceanalytics Modul wiederum durcheinander bringt und dadurch mir inzwischen negative Kosten und Verbräuche für die Daten berechnet werden.
Das Verhalten hat sich nach dem Update von der 1.3.1 kommend geändert.

Optimal wäre es, wenn man auswählen könnte, ob oder in welchem Intervall das Reset erfolgt.

**Comment by Omega236** [comment]
Hat der datenpunkt virtualpowermeter.0.group_light.Virtual_Energy_Total_group_light einen default wert? Wenn ja bitte mal den default wert löschen. 

Ich schau mir noch an, warum sich das in der Version verändert hat (sollte es eigentlich nicht).

**Comment by Omega236** [comment]
https://github.com/ioBroker/ioBroker.js-controller/issues/863

Da der grouo mittlerweile sein eigener Zähler ist, schlägt das Problem durch

**Comment by daniel-finger** [comment]
Ja, der default Wert stand auf 0. Ich habe den nun gelöscht und werde beobachten und berichten

**Comment by daniel-finger** [comment]
Ich kann bestätigen, das das löschen des default Wertes das Problem behoben hat
