### ISSUE TITLE
Minimal consumption / Standby

### ISSUE THREAD

**Issue by SevenUp666** [Omega236/ioBroker.virtualpowermeter#59]
Einige Geräte haben auch im Standby einen geringen Verbrauch, der nicht 0W ist.
Wäre es möglich, einen Wert für "Minimal consumption" zu integrieren, der beim Zustand "aus" oder "Level 0%" zur Berechnung herangezogen wird?
Als Standard-Wert kann dort die 0 ja bereits stehen und kann beim Bedarf angepasst werden.

Die lineare Berechnung muss dann ebenfalls angepasst werden. z.B.
Min.: 10W
Max.: 100 W
Bei 50% wären es somit (100-10)W * 0,5 = 45W  (statt 50W ohne Berücksichtigung von Min. consumption).

**Comment by Omega236** [comment]
Hallo. 

Das habe ich auch. Hier nutze ich einen zweiten VPM mit Gruppe Standby auf z.B. alive

**Comment by SevenUp666** [comment]
Dann habe ich aber auch 2 Werte pro Verbrauchen? 1x für Standby und 1x für Normalbetrieb. Zielführend ist es ja nicht :-)

**Comment by Omega236** [comment]
#71
