### ISSUE TITLE
Wie richte ich den ein?

### ISSUE THREAD

**Issue by tommyMX** [Omega236/ioBroker.virtualpowermeter#68]
Hallo 

hab den Adapter installiert aber wie binde ich den ein?

Wo hinterlege ich meine Steckdosen, dass er diese findet...

danke Euch

**Comment by mcuiobroker** [comment]
Über die Objektstruktur:
![image](https://user-images.githubusercontent.com/84818934/131972628-2c1d9af2-dc99-4289-a022-868a720d2fe0.png)
Grundsätzlich solltest du solche Fragen im Forum (ioBroker) stellen. Da sind mehrere die dir helfen können.
