### ISSUE TITLE
Update stable version in repo from 1.4.4 to 1.4.6

### ISSUE THREAD

**Issue by GermanBluefox** [Omega236/ioBroker.virtualpowermeter#75]
# Think about update stable version to 1.4.6
**Version**: stable=**1.4.4** (45 days old) => latest=**1.4.6** (30 days old)
**Installs**: stable=**442** (42.06%), latest=**128** (12.18%), total=**1051**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2077)

**Comment by Omega236** [comment]
[#](https://github.com/ioBroker/ioBroker.repositories/pull/1863)
