### ISSUE TITLE
Feature Request: On Datenpunkt mit abfragen 

### ISSUE THREAD

**Issue by Stormbringer11** [Omega236/ioBroker.virtualpowermeter#99]
Hallo,

wäre es vielleicht möglich, dass der Adapter noch abfragt ob eine Lampe eingeschalten ist oder nicht. Hintergrund ist, dass beim Deconz Adapter sich der Level DP bei ausgeschalteten Licht nicht auf 0 % ändert und die Stromkosten dadurch natürlich viel zu hoch berechnet werden. 

https://github.com/Jey-Cee/ioBroker.deconz/issues/334

**Comment by Omega236** [comment]
Hallo, diese Funktion gibt es bereits:

![grafik](https://github.com/Omega236/ioBroker.virtualpowermeter/assets/25373047/50f4ee16-1b36-441d-af5e-8ca4031c11de)
